package Main;

import Main.tools.ZoneCarte;
import Main.tools.ZoneHand;
import java.awt.Point;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pauli
 */
public class Pirate extends javax.swing.JFrame {
    Point TailleZoneHand = new Point(800, 500);
    Image pirateIcon;
    private ArrayList<ZoneCarte> cartes = new ArrayList();
    
    /**
     * Creates new form Pirate
     */
    public Pirate() {
        File path = new File(System.getProperty("user.dir") + "\\src\\main\\java\\resource\\Projet_Pirate_Populaire.jpg");
        try {
            pirateIcon = ImageIO.read(path);
        } catch (IOException ex) {
            Logger.getLogger(Pirate.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        repaint();
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        zoneJeu1.setMainFrame(this);
        zoneHand1.setMainFrame(this);
    }
    
    public void terminerTour(){
        zoneJeu1.finTour();
        debutBundle();
        changerJoueur();
    }
    
    public void changerJoueur(){
        
    }
    
    public void debutBundle(){
        finTourButton.setEnabled(false);
        
        
    }
    
    public void finBundle(){
        
    }
    
    public ArrayList<ZoneCarte> getCartes(){
        return cartes;
    }
    public void addCarte(ZoneCarte carte){
        this.setComponentZOrder(carte, 0);
        this.repaint();
        cartes.add(carte);
    }
    
    public void resetHand(){
        cartes = new ArrayList();
        zoneHand1.reset();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zonePopularite1 = new Main.tools.ZonePopularite();
        zonePV1 = new Main.tools.ZonePV();
        zoneJeu1 = new Main.tools.ZoneJeu();
        zoneHand1 = new Main.tools.ZoneHand();
        zoneImageProfil1 = new Main.tools.ZoneImageProfil();
        zoneImageProfil2 = new Main.tools.ZoneImageProfil();
        zonePopularite2 = new Main.tools.ZonePopularite();
        zonePV2 = new Main.tools.ZonePV();
        finTourButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        zoneBundle1 = new Main.tools.ZoneBundle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PiratePopulaire");
        setIconImage(pirateIcon);
        setResizable(false);

        javax.swing.GroupLayout zonePopularite1Layout = new javax.swing.GroupLayout(zonePopularite1);
        zonePopularite1.setLayout(zonePopularite1Layout);
        zonePopularite1Layout.setHorizontalGroup(
            zonePopularite1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        zonePopularite1Layout.setVerticalGroup(
            zonePopularite1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout zonePV1Layout = new javax.swing.GroupLayout(zonePV1);
        zonePV1.setLayout(zonePV1Layout);
        zonePV1Layout.setHorizontalGroup(
            zonePV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        zonePV1Layout.setVerticalGroup(
            zonePV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        zoneJeu1.setPreferredSize(new java.awt.Dimension(750, 300));

        zoneImageProfil1.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout zoneImageProfil1Layout = new javax.swing.GroupLayout(zoneImageProfil1);
        zoneImageProfil1.setLayout(zoneImageProfil1Layout);
        zoneImageProfil1Layout.setHorizontalGroup(
            zoneImageProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        zoneImageProfil1Layout.setVerticalGroup(
            zoneImageProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        zoneImageProfil2.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout zoneImageProfil2Layout = new javax.swing.GroupLayout(zoneImageProfil2);
        zoneImageProfil2.setLayout(zoneImageProfil2Layout);
        zoneImageProfil2Layout.setHorizontalGroup(
            zoneImageProfil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        zoneImageProfil2Layout.setVerticalGroup(
            zoneImageProfil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout zonePopularite2Layout = new javax.swing.GroupLayout(zonePopularite2);
        zonePopularite2.setLayout(zonePopularite2Layout);
        zonePopularite2Layout.setHorizontalGroup(
            zonePopularite2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        zonePopularite2Layout.setVerticalGroup(
            zonePopularite2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout zonePV2Layout = new javax.swing.GroupLayout(zonePV2);
        zonePV2.setLayout(zonePV2Layout);
        zonePV2Layout.setHorizontalGroup(
            zonePV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        zonePV2Layout.setVerticalGroup(
            zonePV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        finTourButton.setText("fin tour");
        finTourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finTourButtonMouseClicked(evt);
            }
        });

        jButton2.setText("debuter tour");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(zonePV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoneImageProfil2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zonePV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zoneHand1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zonePopularite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zoneImageProfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zonePopularite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finTourButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(zoneJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(zoneBundle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(zoneJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finTourButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(59, 59, 59)
                                .addComponent(zoneBundle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(zonePV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zoneHand1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(zoneImageProfil1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zonePopularite1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zonePopularite2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zoneImageProfil2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zonePV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finTourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finTourButtonMouseClicked
        terminerTour();
    }//GEN-LAST:event_finTourButtonMouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        zoneHand1.spawnCard();
        zoneHand1.spawnCard();
        zoneHand1.spawnCard();
        zoneHand1.spawnCard();
        
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
    
    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g);
        g.drawRect(800, 800, TailleZoneHand.y, TailleZoneHand.x);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pirate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pirate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pirate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pirate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pirate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finTourButton;
    private javax.swing.JButton jButton2;
    private Main.tools.ZoneBundle zoneBundle1;
    private Main.tools.ZoneHand zoneHand1;
    private Main.tools.ZoneImageProfil zoneImageProfil1;
    private Main.tools.ZoneImageProfil zoneImageProfil2;
    private Main.tools.ZoneJeu zoneJeu1;
    private Main.tools.ZonePV zonePV1;
    private Main.tools.ZonePV zonePV2;
    private Main.tools.ZonePopularite zonePopularite1;
    private Main.tools.ZonePopularite zonePopularite2;
    // End of variables declaration//GEN-END:variables
}
