/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.lang.reflect.Array;
import java.util.ArrayList;

import javax.swing.JPanel;

import Main.PirateFrame;
import entities.Carte;

/**
 *
 * @author pauli
 */
public class ZoneBundle extends javax.swing.JPanel {

	private ArrayList<Carte> bundle;
    /**
     * Creates new form Bundle
     */
    public ZoneBundle() {
        initComponents();
    }

    public void setBundle(ArrayList<Carte> bundle) {
    	this.bundle = bundle;
    	zoneCarte1.setCarteNf(bundle.get(0));
        zoneCarte2.setCarteNf(bundle.get(1));
        zoneCarte3.setCarteNf(bundle.get(2));

        zoneCarte1.updateVisuel();
        zoneCarte2.updateVisuel();
        zoneCarte3.updateVisuel();
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        zoneCarte1.desactivate();
        zoneCarte2.desactivate();
        zoneCarte3.desactivate();
        repaint();
    }
    
    public void recalculate(){
        repaint();
        revalidate();
    }
    
    public ArrayList<Carte> getCartes() {
    	ArrayList<Carte> temp = new ArrayList();
    	temp.add(zoneCarte1.getCarteNf());
    	temp.add(zoneCarte2.getCarteNf());
    	temp.add(zoneCarte3.getCarteNf());
		return temp;
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneCarte1 = new Main.tools.ZoneCarte();
        zoneCarte2 = new Main.tools.ZoneCarte();
        zoneCarte3 = new Main.tools.ZoneCarte();

        setBackground(new Color(242, 242, 242, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zoneCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoneCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoneCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(zoneCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(zoneCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(zoneCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.tools.ZoneCarte zoneCarte1;
    private Main.tools.ZoneCarte zoneCarte2;
    private Main.tools.ZoneCarte zoneCarte3;
    // End of variables declaration//GEN-END:variables
}
