/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import entities.Carte;

/**
 *
 * @author pauli
 */
public class ZoneCarte extends javax.swing.JPanel {
    private String desc ="ceci est un texte assez long pour avoir des choses a dire meme beaucoup de choses a dire, enfait cest un test";
    
    private Carte carteNf;
    
    private Image imageCarte;
    private boolean activated = true;
    private boolean moving = false;
    private Point posPrec;
    /**
     * Creates new form Carte
     */
    public ZoneCarte() {
        initComponents();
        try {
            // lire l'image
            imageCarte = ImageIO.read(new File(System.getProperty("user.dir")+"\\src\\resource\\carte_face.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(ZoneImageProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomCarte = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(120, 190));
        setMinimumSize(new java.awt.Dimension(120, 190));
        setPreferredSize(new java.awt.Dimension(120, 190));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        nomCarte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomCarte.setText("NomCarte");

        jLabel1.setText("ceci est un texte assez long pour avoir des choses a dire meme beaucoup de choses a dire, enfait cest un test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nomCarte, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomCarte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("label");
    }// </editor-fold>//GEN-END:initComponents

    public void setCarteNf(Carte carteNf) {
		this.carteNf = carteNf;
	}
    public Carte getCarteNf() {
		return carteNf;
	}
    public void updateVisuel() {
    	nomCarte.setForeground(Color.white);
    	jLabel1.setForeground(Color.white);
    	nomCarte.setText(carteNf.getNom());
        jLabel1.setText("<html>"+carteNf.getDescription()+"</html>");
    }
    
    public void desactivate(){
        moving = false;
        activated = false;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(imageCarte != null){
            imageCarte = imageCarte.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
            g.drawImage(imageCarte, 0, 0, null);
        }
    }
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (activated){
            moving = true;
            posPrec = evt.getPoint();
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        moving = false;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(moving){
            Point newPos = new Point(evt.getPoint().x-posPrec.x, evt.getPoint().y-posPrec.y);
            setLocation(getLocation().x+newPos.x, getLocation().y+newPos.y);
        }
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomCarte;
    // End of variables declaration//GEN-END:variables
}
