/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import java.awt.Container;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author pauli
 */
public class Card extends javax.swing.JPanel {
    //les variables suivantes seront changées par des gets au code eclipse
    private String nomCarte = "nom de carte";
    private String descCarte= "description de la carte de  plusieurs issues possibles";
    private String attCarte = "Attaque: 5";
    private String popCarte = "Popularite: 5"; 
    //-----------------------------------------------------------------------

    /**
     * Creates new form Card
     */
    private boolean inHand = true;
    private boolean moving = false;
    private Point posPrec;
    private Point posDepart;
    private Container zoneHand;
    private JFrame frame;
    
    
    
    public Card() {
        initComponents();
        CardName.setText(nomCarte);
        CardDescription.setText("<html>"+descCarte+"</html>");
        CardAttaque.setText(attCarte);
        CardPopularite.setText(popCarte);
        //getParent().setComponentZOrder(this, 0);
    }

    @Override
    public void addNotify() {
        super.addNotify(); 
        zoneHand = this.getParent();
        frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        System.out.println(zoneHand.toString());
        System.out.println(frame);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardName = new javax.swing.JLabel();
        CardPopularite = new javax.swing.JLabel();
        CardAttaque = new javax.swing.JLabel();
        CardDescription = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(90, 130));
        setMinimumSize(new java.awt.Dimension(90, 130));
        setName("Cartes"); // NOI18N
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        CardName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardName.setText("Nom de la carte");

        CardPopularite.setText("Popularité: 0");

        CardAttaque.setText("Attaque: 0");

        CardDescription.setText("zefzerzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CardDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardPopularite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardAttaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CardName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CardDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CardPopularite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CardAttaque)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //co limite zoneHand, co centre carte
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(inHand){
            posPrec = evt.getPoint();
            posDepart = evt.getPoint();
            zoneHand.remove(this);
            frame.add(this);
            moving = true;
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        Point location = getLocation();
        Point CentreCarte = new Point(getLocationOnScreen().x + getWidth()/2
                            ,getLocationOnScreen().y + getHeight()/2);
        Point basDroiteHand = new Point(zoneHand.getLocationOnScreen().x + zoneHand.getWidth()/2
                            ,zoneHand.getLocationOnScreen().y + zoneHand.getHeight()/2);
        
        if (zoneHand.getLocationOnScreen().x<CentreCarte.x && CentreCarte.x<basDroiteHand.x &&
                zoneHand.getLocationOnScreen().y<CentreCarte.y && CentreCarte.y<basDroiteHand.y){
            //toujours dans hand
            moving =false;
            System.out.println("Main.tools.Card.formMouseReleased()\n\n");
            frame.remove(this);
            zoneHand.add(this);
        }else{ 
            if(inHand){
                inHand=false;
                moving =false;
                System.out.println("LIBRE  / / / / /");
            }
        }
        
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (moving) {
            Point newPos = new Point(evt.getPoint().x-posPrec.x, evt.getPoint().y-posPrec.y);
            setLocation(getLocation().x+newPos.x, getLocation().y+newPos.y);
        }
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardAttaque;
    private javax.swing.JLabel CardDescription;
    private javax.swing.JLabel CardName;
    private javax.swing.JLabel CardPopularite;
    // End of variables declaration//GEN-END:variables
}
