/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import java.awt.Container;
import java.awt.Point;

/**
 *
 * @author pauli
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    
    private boolean moving = false;
    private Point posPrec;
    private Point posDepart;
    private Container zoneHand = null;
    Container handParent;
    
    public Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 102, 204));
        setMaximumSize(new java.awt.Dimension(90, 130));
        setMinimumSize(new java.awt.Dimension(90, 130));
        setName("Cartes"); // NOI18N
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //co limite zoneHand, co centre carte
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (zoneHand == null){
            System.out.println("Main.tools.Card.<init>() --- 1");
            zoneHand = this.getParent();
            handParent = zoneHand.getParent();
            System.out.println("Main.tools.Card.<init>() --- 2");
        }
       
        posPrec = evt.getPoint();
        posDepart = evt.getPoint();
        moving = true;
        
        //sortir du parent pour eviter bug
        zoneHand.remove(this);
        handParent.add(this);
        handParent.revalidate();
        handParent.repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        posPrec = evt.getPoint();
        moving = false;
        boolean inHandX = zoneHand.getLocation().x < posPrec.x && 
                zoneHand.getLocation().x+zoneHand.getSize().width < posPrec.x;
        boolean inHandY = zoneHand.getLocation().y < posPrec.y && 
                zoneHand.getLocation().y+zoneHand.getSize().height < posPrec.y;
        
        if (inHandX && inHandY){
            handParent.remove(this);
            zoneHand.add(this);
            zoneHand.revalidate();
            
            setLocation(posDepart);
        }
        else{
            setLocation(posPrec);
            //carte jouée
            System.out.println("carte jouée");
        }
        
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (moving) {
            Point newPos = new Point(evt.getPoint().x-posPrec.x, evt.getPoint().y-posPrec.y);
            setLocation(getLocation().x+newPos.x, getLocation().y+newPos.y);
        }
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
