/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import Main.Pirate;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author pauli
 */
public class ZoneJeu extends javax.swing.JPanel {

    Pirate mainFrame;
    /**
     * Creates new form ZoneJeu
     */
    public ZoneJeu() {
        initComponents();
    }
    
    public void setMainFrame(Pirate mainFrame) {
        this.mainFrame = mainFrame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 0));

        jButton1.setText("fin Partie");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(671, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void finPartie(){
        ArrayList<Carte> cartes = mainFrame.getCartes();
        Point posBasDroite = new Point(getLocation().x+getWidth(),
                                    getLocation().y+getHeight());
        for (int i =0; i<cartes.size(); i++){
            Point cLoc = cartes.get(i).getLocation();
            if(getLocation().x < cLoc.x && cLoc.x < posBasDroite.x &&
                    getLocation().y < cLoc.y && cLoc.y < posBasDroite.y){
                System.out.println("Jouer Carte: "+ cartes.get(i).getName());
            }
            cartes.get(i).setVisible(false);
            mainFrame.remove(cartes.get(i));
        }
        
        System.out.println("penser a supprimer les cartes !!!!!!");
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        finPartie();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}