/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import Main.Pirate;

/**
 *
 * @author pauli
 */
public class ZoneHand extends javax.swing.JPanel {

    /**
     * Creates new form ZoneHand
     */
    private int nbCard = 0;
    private Pirate mainFrame;
    
    public ZoneHand() {
        initComponents();
    }
    
    public void setMainFrame(Pirate mainFrame) {
        this.mainFrame = mainFrame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 102));
        setPreferredSize(new java.awt.Dimension(390, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void reset(){
        nbCard = 0;
    }
    
    public void spawnCard(){
        ZoneCarte newCarte = new ZoneCarte();
        mainFrame.add(newCarte);
        newCarte.setSize(120, 190);
        int unitWidth = getWidth()/5;
        newCarte.setLocation((unitWidth*nbCard)+(unitWidth/5)*(nbCard+1)+getLocation().x,
                (getHeight()-(newCarte.getHeight()/2))/2+getLocation().y);
        mainFrame.addCarte(newCarte);
        nbCard+=1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
