/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.tools;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;



/**
 *
 * @author pauli
 */
public final class ZoneImageProfil extends javax.swing.JPanel {

    private Image photoProfil;
    
    private String pathPirate1 ="\\src\\main\\java\\resource\\Projet_Pirate_Populaire.jpg";
    private String pathPirate2 ="\\src\\main\\java\\resource\\Projet_Pirate_Populaire.jpg";
    
    public ZoneImageProfil() {
        initComponents();
        ajouterImage(true);
    }
    
    public void ChangePlayer(boolean player1){
        ajouterImage(player1);
    }
    
    private void ajouterImage(boolean player1){
        String localPirateAdresse = (System.getProperty("user.dir"));
        File path;
        if (player1){
            path = new File(localPirateAdresse + pathPirate1);
        } else{
            path = new File(localPirateAdresse + pathPirate2);
        }
           
        try {
            // lire l'image
            photoProfil = ImageIO.read(path);
        } catch (IOException ex) {
            Logger.getLogger(ZoneImageProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint(); 
    }   

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(photoProfil != null){
            photoProfil = photoProfil.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
            g.drawImage(photoProfil, 0, 0, null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
